### ISSUE TITLE
C++ compilers?

### ISSUE THREAD

**Issue by bheydarshahi1beyond** [kelvinlawson/dockerfile-hisilicon#1]
Can we compile C++ code too? If so, I would really appreciate it if you could please specify the required steps and commands.

**Comment by kelvinlawson** [comment]
My understanding is it should be able to compile C++ code, using standard GCC methods.

**Comment by bheydarshahi1beyond** [comment]
Thanks, I found the C++ compiler I was looking for at 'arm-linux-hisiv300-g++'

I also have a follow up question. Could please let me know how I can build the above-mentioned compiler in my own Ubuntu computer?
